title: Az Dynamic Groups - Semester Arbeit 01, Dodoe Mannale
description: "Azure Dynamic Groups - Access Governance Concept"
remote_theme: just-the-docs/just-the-docs

url: https://RuminahuiM.github.io/

aux_links:
  JIRA Project: https://heks.atlassian.net/jira/software/c/projects/ADG/summary

footer_content: "Dodoe Ruminahui Mannale - Sem01 - Technische Berufsschule Zürich - Cloud Native Engineering - 2025"
